### ISSUE TITLE
ATI Radeon 5600 Series instead of RX 6900 XT

### ISSUE THREAD

**Issue by LeGyYy** [fkortsagin/Manhunt-Windows-11-Fix#1]
Hello,
i just got Manhunt for Steam and having issues with crashes on Windows 11.  I follow your Tutorial and did all the Steps. As I Start the Game without your Fix, on the Manhunt Launcher under Display Adapter I got my RX 6900 XT and in the Game I have Picture but the game crashes at the very beginning while Playing the Intro Sequenz. With your Fix installed I can only choose ATI Radeon HD 5600 Series and have no Picture while the Game is Running. Any Ideas how i can fix this?

**Comment by silentgameplays** [comment]
> Hello,
i just got Manhunt for Steam and having issues with crashes on Windows 11. I follow your Tutorial and did all the Steps. As I Start the Game without your Fix, on the Manhunt Launcher under Display Adapter I got my RX 6900 XT and in the Game I have Picture but the game crashes at the very beginning while Playing the Intro Sequenz. With your Fix installed I can only choose ATI Radeon HD 5600 Series and have no Picture while the Game is Running. Any Ideas how i can fix this?


1. You will need these dependencies to run the game under Windows 10/11  **Direct Play** and **.NET 3.5**,to install them you need to go into **Control Panel>Programs>Programs and Features>Turn Windows Features on or off>Legacy Components>Enable Direct Play .NET 3.5 Framework support** tick the boxes near them,then wait for Windows Update to download them and restart the PC after they are downloaded and installed. **NB!** There is a weird bug that can occur on Windows 11 when Windows Update says it installed these dependencies,but in reality it did not install them,so repeat the process just in case until you have both **Direct Play** and **.NET 3.5 Framework** installed properly. Make sure your AMD Catalyst drivers are up to date and support Vulkan API.

3. These are the main files you need for the fix to work **Manhunt Fix.bat,d3d8.dll, d3d8.ini, wined3d.dll, global.ini, link.exe, mspdb80.dll,patchrun.bat**  This a sound enhancement option **oalinst.exe**

4.  Make sure you run the **Manhunt Fix.bat** after copying it and the other files stated in step 2 into the Steam game folder, something like **C:\Program Files (x86)\Steam\steamapps\common\Manhunt\**

5. You can do it on a **"fresh install"** of the game ,**"fresh install"** means uninstalling Manhunt from Steam then removing **Manhunt** folder from **C:\Program Files (x86)\Steam\steamapps\common\**

6. There is another repository with alternative additional folders with ThirteenAG's Widescreen wrapper patch,Reshade wrapper with the usage of ThirteenAG  Widescreen patch and universal ermaccers sound fix,use the folder you wish and check if it works.if if does not you can always do a **"fresh install"** of the game described in step 4 using any of the fixes provided:  
https://github.com/fkortsagin/Manhunt-Fix-Alternative

Thank you for the feedback. Hope this solves the issues you are having!

**Comment by LeGyYy** [comment]
Thank You for your fast Response.

I did all the Steps u mentioned again, go to Steam uninstall Manhunt, delete the Folder in *C:\Program Files (x86)\Steam\steamapps\common*.

Net. framework 3.5 and direct Play are enabled, aswell the optional Boxes, WCF HTTP Activation and WCF Not HTTP Activation.

Manhunt reinstall.

Copying all the Files from the Manhunt-Windows-11-Fix-main Folder to Manhunt.

Running Manhunt Fix.bat

And still, when i Try to Start the Game, in the Manhunt Launcher is ATI 5600 series instead of my RX 6900 XT.

I choose a Resolution and Start the Game and No Picture, just Sound is Running.

Is this maybe a Problem with AMD Card? Do you have Nvidia?


Best regards and Thanks for your time.

**Comment by silentgameplays** [comment]
> And still, when i Try to Start the Game, in the Manhunt Launcher is ATI 5600 series instead of my RX 6900 XT.

You have AMD CPU with internal APU  as well correct? Is there any option in the AMD GPU Control Panel to set the Manhunt game to use the RX 6900 XT instead of 5600 of the CPU? My guess would be that game just uses  your CPU integrated 5600 GPU instead of the RX 6900 XT and 5600 does not support Vulkan.

**Comment by LeGyYy** [comment]
I have Ryzen 7 3800X there is no APU. only RX 6900 XT.

**Comment by silentgameplays** [comment]
> I have Ryzen 7 3800X there is no APU. only RX 6900 XT.

I meant your Ryzen 7 3800 seems to have integrated GPU in it,can you go into the AMD Catalyst Control panel and set RX6900 XT as main GPU? If you have steam/discord I can remote into your machine and try to help you out with teamviewer.

**Comment by LeGyYy** [comment]
For communication with other components in the machine, Ryzen 7 3800X uses a PCI-Express Gen 4 connection. This processor does not have integrated graphics, you will need a separate graphics card.

From google

**Comment by silentgameplays** [comment]
> For communication with other components in the machine, Ryzen 7 3800X uses a PCI-Express Gen 4 connection. This processor does not have integrated graphics, you will need a separate graphics card.
> 
> From google

What other options does Manhunt display when you are trying to play it besides 5600 HD? does it show your RX 6900 XT card?

**Comment by LeGyYy** [comment]
I have not AMD Catalyst, its called AMD Software: Adenalin Edition. I was searching for the Option u mentioned but cant find any of this. I know Nvidia has that option because in the past i had a GTX 1660 Super.

**Comment by silentgameplays** [comment]
> I have not AMD Catalyst, its called AMD Software: Adenalin Edition. I was searching for the Option u mentioned but cant find any of this. I know Nvidia has that option because in the past i had a GTX 1660 Super.

It used to be called Catalyst at some point,but yes Adrenalin,does Adrenalin have something similar to a Control Panel from NVIDIA where you can put your main GPU for a game?

How do I get to the AMD control panel?
This can be done in any of the following ways:

    Right click on your desktop and select AMD Radeon Settings.
    Click on the Radeon Settings icon in the System Tray.
    Select AMD Radeon Settings from the Programs menu.

from google

**Comment by LeGyYy** [comment]
If i Click on Display Adapter, it shows only ATI 5600 Series, no other Option.

Without the Fix it shows my RX 6900 XT only, no ATI 5600 Series, but Game is crashing after some minutes while playing.

**Comment by silentgameplays** [comment]
> If i Click on Display Adapter, it shows only ATI 5600 Series, no other Option.
> 
> Without the Fix it shows my RX 6900 XT only, no ATI 5600 Series, but Game is crashing after some minutes while playing.

Because the game does not seem to detect your actual GPU RX 6900 XT and sees it as ATI 5600 GPU. Do you have all the AMD drivers up to date?

**Comment by LeGyYy** [comment]
It has Something like that yes, in the Gaming Section there are all of my Games and i can choose different options like Anti Aliasing and so on but No i cant select my GPU there like Nvidia does.

**Comment by LeGyYy** [comment]
Yes its up to Date.

**Comment by LeGyYy** [comment]
Without the Fix it is Detecting my GPU but with it Doesnt. I will Try something Now. I uninstall Manhunt again. Delete the Folder. Reinstall it. Then Starting the Game once without the fix, so the game recognize my GPU, or it can detect it. Afer that install the Fix.

**Comment by silentgameplays** [comment]
> Without the Fix it is Detecting my GPU but with it Doesnt. I will Try something Now. I uninstall Manhunt again. Delete the Folder. Reinstall it. Then Starting the Game once without the fix, so the game recognize my GPU, or it can detect it. Afer that install the Fix.

Sounds good,maybe it will work. You can also try additional repo's folders

https://github.com/fkortsagin/Manhunt-Fix-Alternative

And manhunt fixer patch from ermaccer(might be some false positives here and there):

https://github.com/ermaccer/Manhunt.Fixer/releases/tag/1.0.6

**Comment by LeGyYy** [comment]
Ok i tried what i wrote before but no Success. Finally I got it to Work with the Manhunt fixer patch from ermaccer. The Next and Last Step is to Copy and Paste the Sound fix, then i should be good to go i guess.

 Much Thanks!

Best regards From Germany

**Comment by silentgameplays** [comment]
> Ok i tried what i wrote before but no Success. Finally I got it to Work with the Manhunt fixer patch from ermaccer. The Next and Last Step is to Copy and Paste the Sound fix, then i should be good to go i guess.
> 
> Much Thanks!
> 
> Best regards From Germany

Glad it worked!
Thank you for the great feedback!
